// app/(ui)/admin/tl/ver/page.tsx
import { desc } from "drizzle-orm";
import { ExternalLink, PencilLine, PlusIcon } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { SimpleTooltip } from "@/components/tooltip";
import { Button } from "@/components/ui/button";
import { Kbd } from "@/components/ui/kbd";
import { db } from "@/lib/db";
import { tierlistTypes, tierlistVersions } from "@/lib/db/schema";
import { cn } from "@/lib/utils";

export default async function TierlistManagerPage() {
  const types = await db.select().from(tierlistTypes).orderBy(tierlistTypes.id);
  const versionsList = await db
    .select()
    .from(tierlistVersions)
    .orderBy(desc(tierlistVersions.order));
  const vers = types.map((t) => ({
    ...t,
    versions: versionsList.filter((v) => v.type === t.id),
  }));

  return (
    <div className="grow-0 flex flex-col pt-5 gap-2 mx-2">
      <Button className="w-fit" asChild>
        <Link href={`/admin/tl/ver/create`}>
          <PlusIcon />
          <span>Create type</span>
        </Link>
      </Button>
      {vers.map((t) => (
        <div className="flex flex-col gap-1 group/type" key={t.id}>
          <div className="font-semibold text-4xl flex flex-wrap items-center gap-2 w-fit">
            <div className="px-2 py-1 border rounded-md bg-[#2228] flex-auto flex flex-wrap items-baseline gap-x-2">
              <span className="text-nowrap">{t.name}</span>
              <span className="flex items-center gap-1">
                <Kbd>{t.id}</Kbd>
                <span className="text-xs text-muted-foreground">{t.mode}</span>
              </span>
            </div>
            <div className="md:opacity-0 group-hover/type:opacity-100 transition-opacity flex gap-1">
              <SimpleTooltip text="Add version">
                <Button asChild>
                  <Link href={`/admin/tl/ver/${t.id}/create`}>
                    <PlusIcon />
                    <span className="md:hidden">Add</span>
                  </Link>
                </Button>
              </SimpleTooltip>
              <SimpleTooltip text="Edit type">
                <Button variant="outline" asChild>
                  <Link href={`/admin/tl/ver/${t.id}/edit`}>
                    <PencilLine />
                    <span className="md:hidden">Edit</span>
                  </Link>
                </Button>
              </SimpleTooltip>
            </div>
          </div>
          <div className="flex gap-2 flex-wrap">
            {t.versions.map((e) => (
              <div
                key={e.id}
                className={cn(
                  e.image
                    ? "relative aspect-video w-[calc(100svw-16px)] md:w-60 rounded-sm border group/ver"
                    : "relative flex items-center justify-center aspect-video w-[calc(100svw-16px)] md:w-60 border rounded-sm bg-[#1118] backdrop-blur-xl font-bold text-4xl group/ver",
                  e.hidden && "opacity-50",
                )}
              >
                {e.image ? (
                  <>
                    <Image
                      src={`/cdn/${e.image}`}
                      alt={e.name}
                      fill
                      className="rounded-sm border object-cover bg-primary -z-1"
                    />
                    <div className="flex absolute w-full justify-center bottom-0 py-1 bg-card rounded-b-sm gap-1">
                      {e.name} <Kbd>{e.id}</Kbd>
                    </div>
                  </>
                ) : (
                  e.name
                )}
                <div className="md:opacity-0 group-hover/ver:opacity-100 transition-opacity flex gap-1 absolute top-1 right-1">
                  <SimpleTooltip text="Open in admin">
                    <Button variant="outline" asChild className="bg-card!">
                      <Link href={`/tl/${t.id}/${e.id}/admin`} target="_blank">
                        <ExternalLink />
                        <span className="md:hidden">Open</span>
                      </Link>
                    </Button>
                  </SimpleTooltip>
                  <SimpleTooltip text="Edit version">
                    <Button variant="outline" asChild className="bg-card!">
                      <Link href={`/admin/tl/ver/${t.id}/${e.id}/edit`}>
                        <PencilLine />
                        <span className="md:hidden">Edit</span>
                      </Link>
                    </Button>
                  </SimpleTooltip>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// src/routes/admin/tl/ver/+page.svelte
<script lang="ts">
  import { ExternalLink } from "lucide-svelte";
  import { Button } from "$lib/components/ui/button";
  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head>
  <title>Tierlist Versions</title>
</svelte:head>

<div class="grid gap-6 p-4">
  <h1 class="text-3xl font-bold">Tierlist Versions</h1>

  {#each data.types as type}
    <section class="grid gap-3">
      <div class="flex flex-wrap items-baseline gap-2">
        <h2 class="text-2xl font-semibold">{type.name}</h2>
        <span class="rounded border px-1.5 py-0.5 font-mono text-xs text-muted-foreground">
          {type.id}
        </span>
        <span class="text-xs text-muted-foreground">{type.mode}</span>
      </div>
      <div class="grid grid-cols-[repeat(auto-fill,minmax(min(15rem,100%),1fr))] gap-3">
        {#each type.versions as version}
          <article
            class={[
              "overflow-hidden rounded-xl border bg-card/70 shadow-sm backdrop-blur",
              version.hidden && "opacity-55",
            ]}
          >
            <div class="relative aspect-video bg-black/20">
              {#if version.image}
                <img class="h-full w-full object-cover" src={`/cdn/${version.image}`} alt={version.name} />
              {:else}
                <div class="flex h-full items-center justify-center text-3xl font-bold">
                  {version.name}
                </div>
              {/if}
            </div>
            <div class="flex items-center justify-between gap-2 p-3">
              <div class="min-w-0">
                <div class="truncate font-semibold">{version.name}</div>
                <div class="truncate font-mono text-xs text-muted-foreground">
                  {version.id} · order {version.order}
                </div>
              </div>
              <Button
                variant="outline"
                size="icon"
                href={`/tl/${type.id}/${version.id}/admin`}
                target="_blank"
                rel="noreferrer"
              >
                <ExternalLink class="size-4" />
              </Button>
            </div>
          </article>
        {/each}
      </div>
    </section>
  {/each}
</div>
