// app/tl/[type]/page.tsx
import { and, eq } from "drizzle-orm";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { tierlistTypes, tierlistVersions } from "@/lib/db/schema";

export default async function TierlistSelectionPage({
  params,
}: {
  params: Promise<{ type: string }>;
}) {
  const { type: typeName } = await params;
  const [type] = await db
    .select()
    .from(tierlistTypes)
    .where(and(eq(tierlistTypes.id, typeName)));
  if (!type) notFound();
  const versions = await db
    .select()
    .from(tierlistVersions)
    .where(
      and(
        eq(tierlistVersions.hidden, false),
        eq(tierlistVersions.type, typeName),
      ),
    );
  return (
    <div className="w-full min-h-full flex justify-center">
      <div className="min-h-full flex flex-col items-center justify-center gap-2">
        <div className="grid gap-1">
          <center className="font-bold text-4xl">{type.name}</center>
          <div className="flex gap-2 flex-wrap justify-center">
            {[
              ...versions.map((e) => ({ ...e, id: `${e.id}1` })),
              ...versions.map((e) => ({ ...e, id: `${e.id}2` })),
              ...versions.map((e) => ({ ...e, id: `${e.id}3` })),
              ...versions.map((e) => ({ ...e, id: `${e.id}4` })),
              ...versions.map((e) => ({ ...e, id: `${e.id}6` })),
            ].map((e) =>
              e.image ? (
                <Link href={`/tl/${type.id}/${e.id}`} key={e.id}>
                  <div className="relative aspect-video w-80 rounded-sm border">
                    <Image
                      src={`/cdn/${e.image}`}
                      alt={e.name}
                      fill
                      className="rounded-sm border object-cover bg-primary"
                    />
                    <div className="flex absolute w-full justify-center bottom-0 py-1 bg-card rounded-b-sm">
                      {e.name}
                    </div>
                  </div>
                </Link>
              ) : (
                <Link href={`/tl/${type.id}/${e.id}`} key={e.id}>
                  <div className="flex items-center justify-center aspect-video w-80 border rounded-sm bg-[#1118] backdrop-blur-xl font-bold text-4xl">
                    {e.name}
                  </div>
                </Link>
              ),
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/tl/[type]/+page.svelte
<script lang="ts">
  import { ArrowLeft } from "lucide-svelte";
  import FadeImage from "$lib/components/FadeImage.svelte";
  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head>
  <title>จัดเทียร์ลิสต์ {data.type.name}</title>
</svelte:head>

<div class="mx-auto flex min-h-full max-w-7xl flex-col gap-6 px-4 py-8">
  <section class="flex flex-col gap-1">
    <a href="/tl" class="flex cursor-default text-muted-foreground hover:underline">
      <ArrowLeft /> กลับไปหน้าแรก
    </a>
    <div class="text-4xl font-bold">
      <div class="w-fit rounded-md border bg-[#2228] px-2 py-1">
        {data.type.name}
        <span class="ml-2 text-sm text-muted-foreground">{data.type.mode}</span>
      </div>
    </div>
    <div class="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {#each data.type.versions as version}
        <a href={`/tl/${data.type.id}/${version.id}`}>
          {#if version.image}
            <div class="relative aspect-video w-full overflow-hidden rounded-lg border">
              <FadeImage
                src={`/cdn/${version.image}`}
                alt={version.name}
                class="h-full w-full rounded-sm border bg-primary object-cover"
              />
              <div class="absolute bottom-0 flex w-full justify-center rounded-b-sm bg-black/50 py-1">
                {version.name}
              </div>
            </div>
          {:else}
            <div class="flex aspect-video items-center justify-center rounded-sm border bg-[#1118] text-5xl font-bold backdrop-blur-xl">
              {version.name}
            </div>
          {/if}
        </a>
      {/each}
    </div>
  </section>
</div>
