// src/routes/(widgets)/widget/donate/goal/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import WidgetVersion from "../../WidgetVersion.svelte";
  import { getDonateBar } from "../widget.remote";

  const barQuery = getDonateBar();
  type Bar = NonNullable<typeof barQuery.current>;
  let bar = $state<Bar>();
  let text = $state<HTMLDivElement>();
  let stableSize: Record<string, number> = {};
  let fitTimer: number | undefined;
  const attachText: Attachment<HTMLDivElement> = (element) => {
    text = element;
  };
  const ratio = $derived(Math.min(1, Number(bar?.amount ?? 0) / (bar?.goal ?? 1)));

  function fit() {
    window.clearInterval(fitTimer);
    if (!text || !bar) return;
    const element = text;
    const key = `${bar.goal}`;
    if (stableSize[key]) {
      element.style.fontSize = `${stableSize[key]}px`;
      element.style.opacity = "1";
      return;
    }
    let fontSize = 48;
    let count = 0;
    element.style.opacity = "0";
    fitTimer = window.setInterval(() => {
      const parent = element.parentElement;
      if (!parent) return;
      fontSize = (fontSize * parent.clientHeight) / element.scrollHeight;
      element.style.fontSize = `${fontSize}px`;
      if (++count > 10) {
        stableSize[key] = fontSize;
        element.style.opacity = "1";
        window.clearInterval(fitTimer);
      }
    }, 100);
  }

  async function update(delayed = false) {
    await barQuery.refresh();
    if (delayed && text) await new Promise((resolve) => setTimeout(resolve, 10000));
    bar = barQuery.current;
    fit();
  }

  onMount(() => {
    const source = new EventSource("/sse/donate");
    source.addEventListener("update", () => void update(true));
    source.addEventListener("ping", () => void update(true));
    source.addEventListener("refresh", () => location.reload());
    const backup = window.setInterval(() => void update(), 300000);
    const resize = () => {
      stableSize = {};
      fit();
    };
    window.addEventListener("resize", resize);
    void barQuery.then((value) => {
      bar = value;
      queueMicrotask(fit);
    });
    return () => {
      source.close();
      window.clearInterval(backup);
      window.clearInterval(fitTimer);
      window.removeEventListener("resize", resize);
    };
  });
</script>

{#if bar}
  <div class="relative h-full max-h-[20svw] w-full overflow-hidden rounded-full bg-[#252525]">
    <div class="absolute inset-2 rounded-full bg-black"></div>
    <div
      class="goal-fill absolute inset-1.5 rounded-full bg-linear-to-b from-[#FD0000] to-[#830000]"
      style:width={`calc(${ratio * 100}% - ${ratio * 12}px)`}
    ></div>
    <div
      {@attach attachText}
      class="absolute top-1/2 right-8 -translate-y-1/2 pb-1 font-bold opacity-0 transition-opacity"
    >
      {bar.goal}฿
    </div>
  </div>
{/if}
<WidgetVersion />

<style>
  .goal-fill {
    transition: width 0.3s ease;
  }
</style>

// app/widget/donate/goal/page.tsx
"use client";

import { sse } from "@/lib/db/sse-endpoints";
import { useEffect, useRef, useState } from "react";
import { getDonateBar } from "./api";
import { motion } from "motion/react";

type Data = Awaited<ReturnType<typeof getDonateBar>>;

export default function TopDonateWidget() {
  const [bar, setBar] = useState<Data>();
  const textRef = useRef<HTMLDivElement | null>(null);
  const stableSize = useRef<Record<string, number>>({});
  const [resizeTick, setResizeTick] = useState(0);

  useEffect(() => {
    async function update() {
      void getDonateBar().then(setBar);
    }
    queueMicrotask(update);
    const { clean } = sse.donate.subMany({
      update,
      ping: update,
      refresh: () => location.reload(),
    });

    const backupInterval = setInterval(update, 300000);

    return () => {
      clean();
      clearInterval(backupInterval);
    };
  }, []);

  // the most idiomatic way possible but it works
  useEffect(() => {
    // oxlint-disable-next-line no-unused-expressions
    resizeTick; // trigger re-run on window resize
    if (!textRef.current) return;
    var fontSize = 48,
      count = 0;
    const el = textRef.current,
      parent = el.parentElement!,
      key = `${bar?.goal}`;
    if (stableSize.current[key]) {
      el.classList.add("opacity-100");
      el.style.fontSize = `${stableSize.current[key]}px`;
      return;
    }
    el.classList.remove("opacity-100");
    const interval = setInterval(() => {
      console.log(el.scrollHeight, parent.clientHeight);
      fontSize = (fontSize * parent.clientHeight) / el.scrollHeight;
      el.style.fontSize = `${fontSize}px`;
      count++;
      if (count > 10) {
        stableSize.current[key] = fontSize;
        el.classList.add("opacity-100");
        clearInterval(interval);
      }
    }, 100);
    return () => {
      el.classList.add("opacity-100");
      clearInterval(interval);
    };
  }, [bar, resizeTick]);

  useEffect(() => {
    const onResize = () => {
      stableSize.current = {};
      setResizeTick((t) => t + 1);
    };
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, [bar]);

  return bar && bar.amount !== null && bar.goal ? (
    <div className="relative h-full max-h-[20svw] w-full rounded-full bg-[#252525]">
      <div className="absolute inset-2 rounded-full bg-black" />
      <motion.div
        className="absolute inset-1.5 rounded-full bg-linear-to-b from-[#FD0000] to-[#830000]"
        animate={{
          width: `calc(${Math.min(1, Number(bar.amount) / bar.goal) * 100}% - 12px)`,
        }}
        initial={{
          width: 0,
        }}
      />
      <div
        ref={textRef}
        className="absolute top-1/2 right-8 -translate-y-1/2 pb-1 font-bold opacity-0 transition-opacity"
      >
        {bar.goal}฿
      </div>
    </div>
  ) : (
    ""
  );
}
