// src/lib/components/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import {
    Tooltip as ShadTooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
  } from "$lib/components/ui/tooltip";

  let {
    text,
    side = "top",
    children,
  }: {
    text: string;
    side?: "top" | "bottom" | "left" | "right";
    children?: Snippet;
  } = $props();
</script>

<TooltipProvider>
  <ShadTooltip>
    <TooltipTrigger>
      {#snippet child({ props })}
        <span {...props} class="inline-flex">
          {@render children?.()}
        </span>
      {/snippet}
    </TooltipTrigger>
    <TooltipContent {side} sideOffset={6}>
      {text}
    </TooltipContent>
  </ShadTooltip>
</TooltipProvider>

// components/tooltip.tsx
"use client";

import type { ReactNode } from "react";
import { Tooltip, TooltipContent, TooltipTrigger } from "./ui/tooltip";

export function SimpleTooltip({
  text,
  children,
  side,
  ...props
}: {
  text?: ReactNode;
  side?: "top" | "right" | "bottom" | "left" | undefined;
} & React.ComponentProps<typeof Tooltip>) {
  return (
    <Tooltip {...props}>
      <TooltipTrigger asChild>{children}</TooltipTrigger>
      <TooltipContent side={side}>{text}</TooltipContent>
    </Tooltip>
  );
}
