// src/routes/(widgets)/widget/donate/+page.svelte
<script lang="ts">
  import posthog from "posthog-js";
  import { onMount } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import { fade } from "svelte/transition";
  import WidgetVersion from "../WidgetVersion.svelte";
  import { markDone, markRunning } from "./widget.remote";

  type DonateData = {
    id: string;
    name: string;
    image?: string;
    amount: number;
    message: string;
  };

  let current = $state<DonateData>();
  let visible = $state(false);
  let sfx: HTMLAudioElement;
  const attachSfx: Attachment<HTMLAudioElement> = (element) => {
    sfx = element;
  };
  const onQueue: string[] = [];
  let queue = Promise.resolve();

  const wait = (time: number) => new Promise<void>((resolve) => setTimeout(resolve, time));

  function enqueue(data: DonateData) {
    if (!data || onQueue.includes(data.id)) return;
    onQueue.push(data.id);
    queue = queue.then(() => ping(data).catch(console.error));
  }

  async function ping(data: DonateData) {
    current = data;
    const { name, amount, message } = data;
    const key = new URLSearchParams(location.search).get("key") ?? "";
    void markRunning({ id: data.id, key });
    const tts = new Audio(`/api/tts?message=${encodeURIComponent(`"${name} โดเนทมา ${amount} บาท.. ${message}"`)}&key=${key}`);
    tts.load();
    const ttsAvailable = await new Promise<boolean>((resolve) => {
      tts.onloadeddata = () => resolve(true);
      tts.onerror = () => resolve(false);
      setTimeout(() => resolve(false), 120000);
    });
    if (!ttsAvailable) posthog.capture("donation_widget_tts_failed", { amount });

    visible = true;
    posthog.capture("donation_widget_displayed", {
      amount,
      name_length: name.length,
      has_image: !!data.image,
    });
    if (sfx) {
      void sfx.play();
      await new Promise<void>((resolve) => (sfx.onended = () => resolve()));
    }
    void tts.play();
    if (ttsAvailable) await new Promise<void>((resolve) => (tts.onended = () => resolve()));

    void markDone({ id: data.id, key });
    posthog.capture("donation_widget_animation_end", { amount, tts_available: ttsAvailable });
    await wait(3000);
    visible = false;
    await wait(1200);
    const index = onQueue.indexOf(data.id);
    if (index !== -1) onQueue.splice(index, 1);
  }

  onMount(() => {
    let failed = 0;
    const pendingHeartbeat: Record<number, () => void> = {};
    const source = new EventSource("/sse/donate");
    source.addEventListener("heartbeat", (event) => pendingHeartbeat[JSON.parse(event.data)]?.());
    source.addEventListener("ping", (event) => enqueue(JSON.parse(event.data) as DonateData));
    source.addEventListener("refresh", () => location.reload());
    posthog.capture("donation_widget_connected");

    const interval = window.setInterval(async () => {
      const tag = Math.floor(Math.random() * 1000);
      const heartbeat = new Promise<void>((resolve, reject) => {
        pendingHeartbeat[tag] = resolve;
        setTimeout(reject, 30000);
      });
      try {
        const response = await fetch(`/api/donate/hb?tag=${tag}${failed > 6 ? "&resume=true" : ""}`, {
          method: "PATCH",
          signal: AbortSignal.timeout(15000),
        }).catch(() => undefined);
        if (failed > 6 && response) {
          queueMicrotask(() => {
            if (response.status === 302) void response.json().then(enqueue);
          });
        }
        await heartbeat;
        failed = 0;
      } catch {
        failed++;
        posthog.capture("donation_widget_heartbeat_failure", { fail_count: failed });
        if (failed > 12) {
          void fetch("/widget/donate", {
            signal: AbortSignal.timeout(30000),
            method: "HEAD",
          })
            .then(({ ok }) => {
              if (!ok) throw new Error("NOT OK");
              location.reload();
            })
            .catch(() => console.warn("Wants to reload, but not safe. Retrying later."));
        }
      } finally {
        delete pendingHeartbeat[tag];
      }
    }, 10000);

    return () => {
      source.close();
      window.clearInterval(interval);
    };
  });
</script>

{#if visible && current}
  <div class="flex h-full items-center justify-center" out:fade={{ duration: 1000 }}>
    <div class="relative w-162.5 overflow-hidden">
      <div class="avatar-wrap absolute top-1/2 left-1/2 z-10 -translate-1/2">
        <div class="avatar-expander min-w-32">
          <img
            src={current.image ?? "/favicon.webp"}
            width="128"
            height="128"
            alt="User submission"
            class="aspect-square size-32 shrink-0 rounded-2xl bg-black/50 object-cover"
          />
        </div>
      </div>
      <div class="donate-panel mx-auto flex h-39 max-w-162.5 gap-3 overflow-hidden rounded-4xl bg-black/80">
        <div class="aspect-square size-32 shrink-0 rounded-2xl"></div>
        <div class="flex min-w-0 flex-col text-3xl font-semibold">
          <span class="donate-title whitespace-nowrap text-[#CB5959]">
            {current.name} : <span class="text-[#FFCC00]">โดเนทมา {current.amount}฿</span>
          </span>
          <span class="donate-message h-20 w-full wrap-break-word whitespace-break-spaces {current.message.length > 80 ? 'line-clamp-3 text-xl' : 'line-clamp-2 text-3xl'}">
            {current.message}
          </span>
        </div>
      </div>
    </div>
  </div>
{/if}
<audio src="/assets/donate-sfx.wav" {@attach attachSfx} preload="auto"></audio>
<WidgetVersion />

<style>
  .avatar-wrap {
    animation: avatar-in 1s cubic-bezier(0, 0.55, 0.45, 1) both;
  }
  .avatar-expander {
    animation: avatar-expand 1s 1s cubic-bezier(0, 0.55, 0.45, 1) both;
  }
  .donate-panel {
    animation: panel-expand 1s 1s cubic-bezier(0, 0.55, 0.45, 1) both;
  }
  .donate-title {
    animation: title-in 1s 1s cubic-bezier(0, 0.55, 0.45, 1) both;
  }
  .donate-message {
    animation: message-in 1s 1.5s ease both;
  }
  @keyframes avatar-in {
    from { top: 200%; rotate: 600deg; }
    to { top: 50%; rotate: 0deg; }
  }
  @keyframes avatar-expand {
    from { width: 1px; padding: 0; }
    to { width: 650px; padding: 20px; }
  }
  @keyframes panel-expand {
    from { width: 0; padding: 0; }
    to { width: 100%; padding: 20px; }
  }
  @keyframes title-in {
    from { padding-top: 20px; }
    to { padding-top: 0; }
  }
  @keyframes message-in {
    from { opacity: 0; }
    to { opacity: 1; }
  }
</style>

// app/widget/donate/page.tsx
"use client";

import Image from "next/image";
import { AnimatePresence, motion } from "motion/react";
import posthog from "posthog-js";
import { useEffect, useRef, useState } from "react";
import { VersionCheck } from "@/app/client";
import { cn } from "@/lib/utils";
import { sse } from "@/lib/db/sse-endpoints";
import DefaultImage from "#/favicon.webp";
import { markDone, markRunning } from "./api";

type DonateData = {
  id: string;
  name: string;
  image?: string;
  amount: number;
  message: string;
};

export default function () {
  const [current, setCurrent] = useState<DonateData>();
  const [mounted, setMounted] = useState(false);
  const [failed, setFailed] = useState(0);
  const sfx = useRef<HTMLAudioElement | null>(null);
  const onQueue = useRef<string[]>([]);
  const queue = useRef<Promise<void>>(Promise.resolve());

  function enqueue(data: DonateData) {
    if (onQueue.current.includes(data.id)) return;
    onQueue.current.push(data.id);
    queue.current = queue.current.then(() => ping(data).catch(console.error));
  }

  async function ping(data: DonateData) {
    setCurrent(data);
    const { name, amount, message } = data;
    markRunning(data.id);
    console.log("Requesting TTS");
    const tts = new Audio(
      `/api/tts?message=${encodeURIComponent(`"${name} โดเนทมา ${amount} บาท.. ${message}"`)}&key=${new URLSearchParams(location.search).get("key")}`,
    );
    tts.load();
    console.log("Waiting for response");
    const ttsAvailable = await new Promise(
      (r) => (
        (tts.onloadeddata = () => r(true)),
        (tts.onerror = () => r(false))
      ),
    );
    if (!ttsAvailable)
      posthog.capture("donation_widget_tts_failed", { amount: data.amount });
    console.log("Transitioning in");
    setMounted(true);
    posthog.capture("donation_widget_displayed", {
      amount: data.amount,
      name_length: data.name.length,
      has_image: !!data.image,
    });
    console.log("Running SFX");
    if (sfx.current) {
      const player = sfx.current;
      player.play();
      console.log("Waiting for SFX to end");
      await new Promise((r) => (player.onended = r));
    }
    console.log("Playing TTS");
    tts.play();
    if (ttsAvailable) await new Promise((r) => (tts.onended = r));
    console.log("Done");
    markDone(data.id);
    posthog.capture("donation_widget_animation_end", {
      amount: data.amount,
      tts_available: ttsAvailable,
    });
    await new Promise((r) => setTimeout(r, 3000));
    setMounted(false);
    await new Promise((r) => setTimeout(r, 1200));
    console.log("Handing off");
    onQueue.current = onQueue.current.filter((q) => q !== data.id);
  }

  const { name, amount, message, image } = current ?? {};

  useEffect(() => {
    const pendingHeartbeat: Record<number, (v?: unknown) => void> = {};
    const { clean } = sse.donate.subMany({
      heartbeat: (tag) => pendingHeartbeat[tag]?.(),
      ping: enqueue,
      refresh: () => location.reload(),
    });
    posthog.capture("donation_widget_connected");

    const interval = setInterval(async () => {
      const tag = Math.floor(Math.random() * 1000);
      const promise = new Promise(
        (r, j) => ((pendingHeartbeat[tag] = r), setTimeout(j, 30000)),
      );
      await fetch(`/api/donate/hb?tag=${tag}`, {
        method: "PATCH",
      }).catch(() => {});
      try {
        await promise;
        console.log("Heartbeat OK");
        setFailed(0);
      } catch {
        console.error("Heartbeat timed out");
        setFailed((x) => x + 1);
        posthog.capture("donation_widget_heartbeat_failure", {
          fail_count: failed + 1,
        });
        if (failed > 12) location.reload();
      }
    }, 10000);
    return () => {
      clearInterval(interval);
      clean();
    };
    // ping({
    //   name: "Gayshin",
    //   amount: 1,
    //   message: `เสื้อดำเด้าหน่อย`,
    // });
  }, [failed]);

  return (
    <>
      <AnimatePresence>
        {mounted && (
          <div className="flex h-full items-center justify-center">
            <div className="relative w-162.5 overflow-hidden">
              <motion.div
                className="absolute top-1/2 left-1/2 z-10 -translate-1/2"
                initial={{ top: "200%", rotateZ: "600deg" }}
                animate={{ top: "50%", rotateZ: "0deg" }}
                exit={{ opacity: 0, transition: { delay: 0, duration: 1 } }}
                transition={{ duration: 1, ease: "circOut" }}
              >
                <motion.div
                  className="min-w-32"
                  initial={{ width: "1px", padding: 0 }}
                  animate={{ width: "650px", padding: "20px" }}
                  transition={{ delay: 1, duration: 1, ease: "circOut" }}
                >
                  <Image
                    src={image ?? DefaultImage}
                    width={128}
                    height={128}
                    alt="User submitted image"
                    className="aspect-square size-32 shrink-0 rounded-2xl bg-black/50"
                  />
                </motion.div>
              </motion.div>
              <motion.div
                className="mx-auto flex h-39 max-w-162.5 gap-3 overflow-hidden rounded-4xl bg-black/80 p-5"
                initial={{ width: 0, padding: 0 }}
                animate={{ width: "100%", padding: "20px" }}
                exit={{ opacity: 0, transition: { delay: 0, duration: 1 } }}
                transition={{ delay: 1, duration: 1, ease: "circOut" }}
              >
                <div className="aspect-square size-32 shrink-0 rounded-2xl" />
                <div className="flex min-w-0 flex-col text-3xl font-semibold">
                  <motion.span
                    className="whitespace-nowrap text-[#CB5959]"
                    initial={{ paddingTop: "20px" }}
                    animate={{ paddingTop: 0 }}
                    transition={{ delay: 1, duration: 1, ease: "circOut" }}
                  >
                    {name} :{" "}
                    <span className="text-[#FFCC00]">โดเนทมา {amount}฿</span>
                  </motion.span>
                  <motion.span
                    className={cn(
                      "h-20 w-full wrap-break-word whitespace-break-spaces",
                      (message ?? "").length > 80
                        ? "line-clamp-3 text-xl"
                        : "line-clamp-2 text-3xl",
                    )}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 1.5, duration: 1 }}
                  >
                    {message}
                  </motion.span>
                </div>
              </motion.div>
            </div>
          </div>
        )}
      </AnimatePresence>
      <audio src="/assets/donate-sfx.wav" ref={sfx} preload="auto" />
      <VersionCheck headless />
    </>
  );
}
