// src/routes/login/+page.svelte
<script lang="ts">
import { UserLock } from "lucide-svelte";
import { resolve } from "$app/paths";
import { Button } from "$lib/components/ui/button";
import { Input } from "$lib/components/ui/input";
import type { ActionData, PageData } from "./$types";

let { data, form }: { data: PageData; form: ActionData } = $props();
let email = $state("");
let password = $state("");
</script>

<svelte:head>
  <title>Admin Login</title>
</svelte:head>

<div class="flex min-h-svh items-center justify-center bg-[#1117] p-6 backdrop-blur-lg">
  <form
    class="grid w-full max-w-sm gap-6 rounded-2xl border bg-card/90 p-6 shadow-xl"
    method="POST"
  >
    <input type="hidden" name="next" value={data.next || "/admin"} />

    <div class="flex flex-col items-center gap-2 text-center">
      <a href={resolve("/")} class="flex size-10 items-center justify-center rounded-md">
        <UserLock class="size-7" />
        <span class="sr-only">Buzzy</span>
      </a>
      <h1 class="text-xl font-bold">Welcome to Buzzy.</h1>
      <p class="text-sm text-muted-foreground">
        Sign in with an admin account to continue.
      </p>
      <p class="text-sm">
        Don't have an account?
        <a class="underline underline-offset-4" href="https://cdn.gunshiz.top/signup">Sign Up</a>
      </p>
    </div>

    <label class="grid gap-1">
      <span class="text-sm font-medium">Email</span>
      <Input
        value={email || form?.email || ""}
        oninput={(event) => (email = event.currentTarget.value)}
        name="email"
        type="email"
        autocomplete="email"
        placeholder="m@example.com"
        required
      />
    </label>

    <label class="grid gap-1">
      <span class="text-sm font-medium">Password</span>
      <Input
        bind:value={password}
        name="password"
        type="password"
        autocomplete="current-password"
        required
      />
    </label>

    {#if form?.message}
      <p class="rounded-md border border-destructive/50 bg-destructive/10 p-2 text-sm text-destructive">
        {form.message}
      </p>
    {/if}

    <Button type="submit" class="w-full">
      Login
    </Button>
  </form>
</div>

// app/login/page.tsx
"use client";

import { UserLock } from "lucide-react";
import { useRouter } from "next/navigation";
import { type FormEvent, use } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { authClient } from "@/lib/auth-client";

export default function LoginPage({
  searchParams,
}: {
  searchParams: Promise<{ next?: string }>;
}) {
  const router = useRouter();
  const { next } = use(searchParams);
  const cb = next || "/admin";
  async function submit(ev: FormEvent<HTMLFormElement>) {
    ev.preventDefault();
    const data = new FormData(ev.currentTarget);
    const r = await authClient.signUp
      .email({
        email: data.get("email") as string,
        password: data.get("password") as string,
        name: data.get("name") as string,
      })
      .catch(() => toast.error("Failed to login"));
    if (typeof r !== "object") return toast.error("Invalid email or password");
    if (r.error) return toast.error(r.error.message);
    router.push(cb);
  }
  return (
    <div className="bg-[#1117] backdrop-blur-lg flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
      <div className="w-full max-w-sm">
        <div className="flex flex-col gap-6">
          <form onSubmit={submit}>
            <div className="flex flex-col gap-6">
              <div className="flex flex-col items-center gap-2">
                <a
                  href="/"
                  className="flex flex-col items-center gap-2 font-medium"
                >
                  <div className="flex size-8 items-center justify-center rounded-md">
                    <UserLock className="size-6" />
                  </div>
                  <span className="sr-only">Buzzy</span>
                </a>
                <h1 className="text-xl font-bold">Welcome to Buzzy.</h1>
                <div className="text-center text-sm">
                  Don&apos;t have an account?{" "}
                  <a
                    href="https://cdn.dgnr.us/signup"
                    className="underline underline-offset-4"
                  >
                    Sign Up
                  </a>
                </div>
              </div>
              <div className="flex flex-col gap-3">
                <div className="grid gap-1">
                  <Label htmlFor="email">Name</Label>
                  <Input
                    id="name"
                    name="name"
                    type="text"
                    placeholder="Mr. Buzz"
                    required
                    autoFocus
                  />
                </div>
                <div className="grid gap-1">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    name="email"
                    type="email"
                    placeholder="m@example.com"
                    required
                    autoFocus
                  />
                </div>
                <div className="grid gap-1">
                  <Label htmlFor="password">Password</Label>
                  <Input
                    id="password"
                    name="password"
                    type="password"
                    required
                  />
                </div>
                <Button type="submit" className="w-full">
                  Login
                </Button>
              </div>
            </div>
          </form>
          <div className="text-muted-foreground *:[a]:hover:text-primary text-center text-xs text-balance *:[a]:underline *:[a]:underline-offset-4">
            Any attempts to bruteforce the system
            <br />
            will result in consequences.
          </div>
        </div>
      </div>
    </div>
  );
}
